// Copyright 2025, Evan Palmer
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

#pragma once

#include <gst/gst.h>

#include <camera_info_manager/camera_info_manager.hpp>
#include <geometry_msgs/msg/pose_stamped.hpp>
#include <memory>
#include <opencv2/aruco.hpp>
#include <rclcpp/node.hpp>
#include <rclcpp/rclcpp.hpp>
#include <sensor_msgs/msg/camera_info.hpp>

// auto-generated by generate_parameter_library
#include <barlus_image_pipeline/track_markers_parameters.hpp>

namespace barlus
{

class TrackMarkersNode : public rclcpp::Node
{
public:
  explicit TrackMarkersNode(const rclcpp::NodeOptions & options = rclcpp::NodeOptions());

  ~TrackMarkersNode();

private:
  auto configure_stream() -> bool;

  auto shutdown_stream() -> void;

  std::shared_ptr<track_markers_node::ParamListener> param_listener_;
  track_markers_node::Params params_;

  std::unique_ptr<sensor_msgs::msg::CameraInfo> camera_info_;
  std::shared_ptr<camera_info_manager::CameraInfoManager> camera_info_manager_;
  std::unordered_map<int, std::shared_ptr<rclcpp::Publisher<geometry_msgs::msg::PoseStamped>>> pose_pub_map_;

  GstElement * pipeline_;

  cv::Mat obj_points_;
  cv::Ptr<cv::aruco::Dictionary> dictionary_;
  cv::Ptr<cv::aruco::DetectorParameters> detector_params_;
};

}  // namespace barlus
